### PR TITLE
Do not copy the read count if you duplicate the news

### PR DESCRIPTION
**Pull request by Tastaturberuf**

### CODE REVIEW

**Comment by Tastaturberuf** [comment]
Why? Copying the count make no sense at all.

**Comment by stefanheimes** [comment]
This PR was closed 'cause the branch was merged and removed. It's not yet merged.

@stefanheimes I must check this against the 1.3.0 hotfix branch

**Comment by stefanheimes** [comment]
@Tastaturberuf sorry I have closed it unintentionally I have to add it per hand or can you open it again, against the hotfix/1.3.0?

**Comment by stefanheimes** [comment]
@Tastaturberuf sorry I have closed this unintentionally 'cause I merged and removed the branch. This wasn't on purpose, and I hadn't the time on Friday to finalize this PR, sorry. 

I have merged it in the hotfix/1.3.0 with Contao 4.9 and 4.13 Support and removed PHP Support for 7.4 and add PHP 8.0. 

I have to check it against a current Contao 4.13 but fell free to check it.

**Comment by Tastaturberuf** [comment]
Thank you.

**Pull request closed without merging**
